version: 2
jobs:
  build:
    docker:
      - image: docker:18.01-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build
          command: |
            docker build --target build --tag identicons-build .
            docker build --target production --tag mythmon/identicons:$CIRCLE_SHA1 .
      - run:
          name: Test
          command: docker run identicons-build cargo test
